# Generated by Django 4.1.7 on 2023-04-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraToma',
            fields=[
                ('horaIden', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Identificador')),
                ('horaDate', models.CharField(max_length=20, verbose_name='Fecha')),
                ('horaServ', models.CharField(blank=True, max_length=20, null=True, verbose_name='Servicio')),
            ],
        ),
    ]
