# Generated by Django 4.1.7 on 2023-04-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_horatoma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
